### ISSUE TITLE
Mismatch between fire maps and flaming/smoldering consumption maps

### ISSUE THREAD

**Issue by cjm23** [LANDIS-II-Foundation/Extension-SCRAPPLE#76]
Unburned cells adjacent to fire maps (e.g. day-of-fire, fire-intensity) are incorporated into flaming/smoldering consumption maps.  Example, 1090 burned cells, 1234 flaming/smoldering cells.

**Comment by rmscheller** [comment]
How do you know how many flaming/smoldering cells?  What values are filtering on?

**Comment by rmscheller** [comment]
Mapping needed to add check for Intensity > 0.  Added to all outputs maps.
