### ISSUE TITLE
Creating fire event id map?

### ISSUE THREAD

**Issue by cjm23** [LANDIS-II-Foundation/Extension-SCRAPPLE#77]
One helpful output map would be a map that shows fire by unique event id, which would allow for a spatial/tabular join with the scrapple-event-log (more or less letting the event log become an attribute table).

**Comment by rmscheller** [comment]
Clarification:  And so you want to add an Event ID # to the Event Log as well, correct?

**Comment by cjm23** [comment]
That is correct.  The goal would be to match the each event in the event log to each event on the map fire with the same ID# so that the event log could act as an attribute table in a GIS software.

**Comment by rmscheller** [comment]
Coded and conducted initial runs-to-completion tests.  Installer = 2.0.2.  Needs further testing.
